name: Build and Release Docker Image

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: docker build -t my-web-app:${{ steps.vars.outputs.short_sha }} .

      - name: Save image as a .tar file
        run: docker save my-web-app:${{ steps.vars.outputs.short_sha }} -o my-web-app-${{ steps.vars.outputs.short_sha }}.tar

      - name: Create GitHub Release and upload image
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v-${{ steps.vars.outputs.short_sha }}
          name: Release ${{ steps.vars.outputs.short_sha }}
          files: my-web-app-${{ steps.vars.outputs.short_sha }}.tar